version: "3"
services:
  webserver:
    image: rp
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
        DATABASE: postgres
        POSTGRES_HOST: postgres
        POSTGRES_USER: rp
        POSTGRES_PASSWORD: development
        LOG_LEVEL: INFO
    #command: bash -c "tail -f /dev/null"
    command: bash -c "python manage.py makemigrations app && python manage.py migrate && python manage.py load_testing_data && python manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    depends_on:
      - postgres
    networks:
      - rp-net
    volumes:
      - ${REPO_ROOT}/server:/server

  postgres:
    image: postgres:11.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: rp
      POSTGRES_PASSWORD: development
    ports:
        - "5432:5432"
    networks:
      - rp-net
    volumes:
      - ${REPO_ROOT}/.local/postgres:/var/lib/postgresql/data

# NGINX For SSL Termination or Load Balancing
#  nginx:
#    image: nginx:1.16
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#    ports:
#        - "443:443"
#    depends_on:
#      - webserver
#    networks:
#      - rp-net
#    volumes:
#      - ${REPO_ROOT}/deploy/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
#      - ${REPO_ROOT}/deploy/nginx/web.crt:/etc/nginx/web.crt
#      - ${REPO_ROOT}/deploy/nginx/web.key:/etc/nginx/web.key

networks:
  rp-net:
