version: "3"
services:
  web:
    image: django-starter-web
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
        DATABASE: postgres
        POSTGRES_HOST: postgres
        POSTGRES_USER: base
        POSTGRES_PASSWORD: development
        LOG_LEVEL: INFO
    #command: bash -c "tail -f /dev/null"
    command: bash -c "python manage.py makemigrations app && python manage.py migrate && python manage.py load_sample_data && python manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    depends_on:
      - postgres
    networks:
      - django-starter-net
    volumes:
      - ${REPO_ROOT}/server:/server

  postgres:
    image: postgres:11.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: base
      POSTGRES_PASSWORD: development
    ports:
        - "5432:5432"
    networks:
      - django-starter-net
    volumes:
      - ${REPO_ROOT}/.local/postgres:/var/lib/postgresql/data

networks:
  django-starter-net:
